Dota2_Shop/Controllers/ArtifactsController.cs
using Dota2_Shop.Date;
using Dota2_Shop.Date.Services;
using Dota2_Shop.Date.Static;
using Dota2_Shop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dota2_Shop.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ArtifactsController : Controller       {
        
        private readonly IArtifactsService _service;

        public ArtifactsController(IArtifactsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allArtifacts = await _service.GetAllAsync();
            return View(allArtifacts);
        }

        //Search string
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allArtifacts = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var searchResult = allArtifacts.Where(n => n.ArtifactName.Contains(searchString)).ToList();
                return View("Index", searchResult);
            }

            return View("Index", allArtifacts);
        }

        //Get: Artifacts/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] 
        public async Task<IActionResult> Create([Bind("ArtifactImage, ArtifactName, ArtifactBonus, ArtifactCost, ArtifactDisription")]Artifact artifact)
        {
            if(!ModelState.IsValid)
            {
                return View(artifact);
            }
            await _service.AddAsync(artifact);
            return RedirectToAction(nameof(Index));
        }
        //Get: Artifacts/Detalis/Id
        public async Task<IActionResult> Details(int id)
        {
            var artifactDetails = await _service.GetByIdAsync(id);

            if (artifactDetails == null) return View("NotFound");
            return View(artifactDetails);
        }

        //Get: Artifacts/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var artifactDetails = await _service.GetByIdAsync(id);

            if (artifactDetails == null) return View("NotFound");
            return View(artifactDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id, ArtifactImage, ArtifactName, ArtifactBonus, ArtifactCost, ArtifactDisription")] Artifact artifact)
        {
            if (!ModelState.IsValid)
            {
                return View(artifact);
            }
            await _service.UpdateAsync(id, artifact);
            return RedirectToAction(nameof(Index));
        }

        //Get: Artifacts/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var artifactDetails = await _service.GetByIdAsync(id);
            if (artifactDetails == null) return View("NotFound");
            return View(artifactDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artifactDetails = await _service.GetByIdAsync(id);
            if (artifactDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);            
            return RedirectToAction(nameof(Index));
        }
    }
}

Dota2_Shop/Controllers/HeroController.cs
using Dota2_Shop.Date;
using Dota2_Shop.Date.Services;
using Dota2_Shop.Date.Static;
using Dota2_Shop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Dota2_Shop.Controllers
{
    [Authorize(Roles =UserRoles.Admin)]
    public class HeroController : Controller
    {
        private readonly IHeroesService _service;

        public HeroController(IHeroesService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allHeroes = await _service.GetAllAsync();
            return View(allHeroes);
        }

        //Search string
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allHeroes = await _service.GetAllAsync();

            if (!string.IsNullOrEmpty(searchString))
            {
                var searchResult = allHeroes.Where(n => n.HeroName.Contains(searchString)).ToList();
                return View("Index", searchResult);
            }

            return View("Index", allHeroes);
        }

        //Get: heroes/details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var heroesDetails = await _service.GetByIdAsync(id);

            if (heroesDetails == null) return View("NotFound");
            return View(heroesDetails);
        }
        //Get: heroes/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("HeroImage,HeroName,HeroRole,StreghtAttributes,AgilityAttributes,IntelligenceAttributes,FirstAbility,SecondAbility,ThirdAbility,UltimateAbility,HeroBio")] Hero hero)
        {
            if (!ModelState.IsValid)
            {
                return View(hero);
            }
            await _service.AddAsync(hero);
            return RedirectToAction(nameof(Index));
        }

        //Get: heroes/edit
        public async Task<IActionResult> Edit(int id)
        {
            var heroesDetails = await _service.GetByIdAsync(id);
            if (heroesDetails == null) return View("NotFound");
            return View(heroesDetails);             
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,HeroImage,HeroName,HeroRole,StreghtAttributes,AgilityAttributes,IntelligenceAttributes,FirstAbility,SecondAbility,ThirdAbility,UltimateAbility,HeroBio")] Hero hero)
        {
            if (!ModelState.IsValid) return View(hero);

            if (id == hero.Id)
            {
                await _service.UpdateAsync(id, hero);
                return RedirectToAction(nameof(Index));
            }
            return View(hero);
        }

        //Get: Hero/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var heroesDetails = await _service.GetByIdAsync(id);
            if (heroesDetails == null) return View("NotFound");
            return View(heroesDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var heroesDetails = await _service.GetByIdAsync(id);
            if (heroesDetails == null) return View("NotFound");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
            

    }
}

Dota2_Shop/Controllers/ItemsController.cs
using Dota2_Shop.Date;
using Dota2_Shop.Date.Enum;
using Dota2_Shop.Date.Services;
using Dota2_Shop.Date.Static;
using Dota2_Shop.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Dota2_Shop.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ItemsController : Controller
    {

        private readonly IItemsService _service;

        public ItemsController(IItemsService service)
        {
            _service = service;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allItems = await _service.GetAllAsync(n => n.Hero);
            return View(allItems);
        }

        //Search string
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string searchString)
        {
            var allItems = await _service.GetAllAsync(n => n.Hero);

            if(!string.IsNullOrEmpty(searchString))
            {
                var searchResult = allItems.Where(n => n.ItemName.Contains(searchString)).ToList();
                return View("Index", searchResult);
            }

            return View("Index", allItems);
        }

        //Get Items/Details
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var itemDetails = await _service.GetItemByIdAsync(id);
            return View(itemDetails);
        }

        //Get: Items/Create
        public async Task<IActionResult> Create()
        {
            var itemDropedownsDate = await _service.GetNewItemDropdownsValues();
            ViewBag.Heros = new SelectList(itemDropedownsDate.Heros, "Id", "HeroName");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewItemVM item)
        {
           if(!ModelState.IsValid)
            {
                var itemDropedownsDate = await _service.GetNewItemDropdownsValues();

                ViewBag.Heros = new SelectList(itemDropedownsDate.Heros, "Id", "HeroName");

                return View(item);
            }

            await _service.AddNewItemAsync(item);
            return RedirectToAction(nameof(Index));
        }
        //Get: Items/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var itemDetails = await _service.GetItemByIdAsync(id);
            if(itemDetails == null) return View("NotFound");

            var response = new NewItemVM()
            {
                Id = itemDetails.Id,
                ItemImage = itemDetails.ItemImage,
                ItemName = itemDetails.ItemName,
                ItemPrice = itemDetails.ItemPrice,
                Rarity = itemDetails.Rarity,
                PartOfSet = itemDetails.PartOfSet,
                HeroId = itemDetails.HeroId

            };
            var itemDropedownsDate = await _service.GetNewItemDropdownsValues();
            ViewBag.Heros = new SelectList(itemDropedownsDate.Heros, "Id", "HeroName");
            return View(response);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewItemVM item)
        {
            if (id != item.Id) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var itemDropedownsDate = await _service.GetNewItemDropdownsValues();

                ViewBag.Heros = new SelectList(itemDropedownsDate.Heros, "Id", "HeroName");

                return View(item);
            }

            await _service.UpdateItemAsync(item);
            return RedirectToAction(nameof(Index));
        }

       
    }
}

Dota2_Shop/Controllers/OrdersController.cs
using Dota2_Shop.Date.Cart;
using Dota2_Shop.Date.Services;
using Dota2_Shop.Date.Static;
using Dota2_Shop.Date.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Dota2_Shop.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IItemsService _itemsService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IItemsService itemsService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _itemsService = itemsService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }
        //Add item to cart
        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var scitem = await _itemsService.GetItemByIdAsync(id);
            if(scitem != null)
            {
                _shoppingCart.AddItemToCart(scitem);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        //Remove item from cart
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var scitem = await _itemsService.GetItemByIdAsync(id);
            if (scitem != null)
            {
                _shoppingCart.RemoveItemFromCart(scitem);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }

        //Complete order
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }
    }
}

Dota2_Shop/Views/Shared/NotFound.cshtml
<div class="row text-center">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">This page is not found</h1>
        <hr />
        <a class="btn btn-outline-success" style="text-align: center" asp-controller="Items" asp-action="Index">Back Home</a>
    </div>
</div>

Dota2_Shop/Views/Shared/_CreateButton.cshtml
@model string;
@if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
{
    <div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
        <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
            <i class="bi bi-plus-square"></i> Add New
        </a>
    </div>
}

Dota2_Shop/Views/Shared/_Identity.cshtml
@inject UserManager<ApplicationUser> UserManager;

@if (!User.Identity.IsAuthenticated)
{
    <a class="btn btn-outline-success my-2 my-sm-0" asp-controller="Account" asp-action="Login"><i class="bi bi-house-door"></i> Log in</a>
    <span style="padding: 5px;"></span>
    <a class="btn btn-outline-primary my-2 my-sm-0" asp-controller="Account" asp-action="Register"><i class="bi bi-person-plus"></i> Register </a>         
}
else
{
    <div class="dropdown">
        <button class="btn btn-outline-success dropdown-toggle" type="button" id="profile-btn" data-toggle="dropdown"
            aria-expanded="false">
            <i class="bi bi-collection"></i> Hello @UserManager.GetUserName(User)
        </button>
        <ul class="dropdown-menu" aria-labelledby="profile-btn">
            <li>
                <a class="dropdown-item" asp-controller="Orders" asp-action="Index">
                    <i class="bi bi-list"></i> Orders
                </a>
            </li>
            @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
            {
                <li>
                    <a class="dropdown-item" asp-controller="Account" asp-action="Users">
                    <i class="bi bi-people"></i> Users
                </a>
                </li>
            }
        </ul>
    </div>

    <span style="padding: 5px;"></span>
    <form asp-controller="Account" asp-action="Logout">
        <button class="btn btn-outline-danger my-2-sm-0">
            <i class="bi bi-door-open"></i> Log out
        </button>
    </form>
}

Dota2_Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dota2_Shop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" type="text/css"/>
    <link rel="stylesheet" href="~/css/Style.css" type="text/css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Dota2_Shop.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Items" asp-action="Index">Dota 2 Shop</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                          <li class="navbar-nav flex-grow-1">
                            <a class="nav-link text-dark" asp-controller="Items" asp-action="Index"> <i class="bi bi-shop-window"></i> Items &nbsp;</a>
                            <a class="nav-link text-dark" asp-controller="Hero" asp-action="Index"> <i class="bi bi-person-vcard"></i> Heroes &nbsp;</a>
                            <a class="nav-link text-dark" asp-controller="Artifacts" asp-action="Index"> <i class="bi bi-heart-arrow"></i> Artifacts &nbsp;</a>
                          </li>
                    </ul>

                    <form class="form-inline my-2 my-lg-0" asp-action="Filter" style="padding-right: 25px;">
                        <div class="input-group">
                           <input name="searchString" type="text" class="form-control mr-sm-2" placeholder="Search..."/>
                           <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-binoculars"></i></button>
                        </div>
                       </form>

                       <ul class="navbar-nav">
                        @await Component.InvokeAsync("ShoppingCartIcon")
                       </ul>

                   
                   <partial name="_Identity.cshtml"></partial>

                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @*<footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Dota2_Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/bootstrap.min.js" asp-append-version="true"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>